extends Node

signal player_stats_changed()
signal player_country_changed()
var countries: Dictionary[String, CountryData] = {}
var player_country: CountryData

func _ready() -> void:
	await get_tree().process_frame
	MainClock.day_passed.connect(_on_day_passed)


func _on_day_passed() -> void:
	# Loop through every country instance in the dictionary
	for c_name: String in countries:
		var country_obj: CountryData = countries[c_name]
		country_obj.process_turn()
	player_stats_changed.emit()


func initialize_countries() -> void:
	countries.clear()
	
	# 1. Get the list of countries generated by MapManager
	# MapManager.country_to_provinces keys are the valid countries found on the map image
	var detected_countries = MapManager.country_to_provinces.keys()
	
	if detected_countries.is_empty():
		push_warning("CountryManager: No countries detected in MapManager!")
		# Fallback to the colors list if map generation failed or is empty
		detected_countries = MapManager.COUNTRY_COLORS.keys()

	# 2. Create a CountryData instance for each
	for country_name in detected_countries:
		var new_country := CountryData.new(country_name)
		add_child(new_country)
		countries[country_name] = new_country
		
	print("CountryManager: Initialized %d countries." % countries.size())


func get_country(c_name: String) -> CountryData:
	c_name = c_name.to_lower()
	if countries.has(c_name):
		return countries[c_name]
	push_error("CountryManager: Requested non-existent country '%s'" % c_name)	
	return null


# In CountryManager.gd

func set_player_country(country_name: String) -> void:
	var country := countries.get(country_name.to_lower()) as CountryData
	if !country:
		push_error("CountryManager: Requested non-existent country '%s'" % country_name)
		return

	# Disable AI for the previous player country (if switching is allowed)
	if player_country:
		player_country.is_player = false

	player_country = country
	player_country.is_player = true # <--- IMPORTANT: Disable AI for this country
	
	print("Player is now playing as: ", country_name)
	emit_signal("player_country_changed")
